export const BEAT_LIST_REQUEST = 'BEAT_LIST_REQUEST'
export const BEAT_LIST_SUCCESS = 'BEAT_LIST_SUCCESS'
export const BEAT_LIST_FAIL = 'BEAT_LIST_FAIL'

export const BEAT_DETAILS_REQUEST = 'BEAT_DETAILS_REQUEST'
export const BEAT_DETAILS_SUCCESS = 'BEAT_DETAILS_SUCCESS'
export const BEAT_DETAILS_FAIL = 'BEAT_DETAILS_FAIL'

export const BEAT_DELETE_REQUEST = 'BEAT_DELETE_REQUEST'
export const BEAT_DELETE_SUCCESS = 'BEAT_DELETE_SUCCESS'
export const BEAT_DELETE_FAIL = 'BEAT_DELETE_FAIL'

export const BEAT_ADD_REQUEST = 'BEAT_ADD_REQUEST'
export const BEAT_ADD_SUCCESS = 'BEAT_ADD_SUCCESS'
export const BEAT_ADD_FAIL = 'BEAT_ADD_FAIL'
export const BEAT_ADD_RESET = 'BEAT_ADD_RESET'

export const BEAT_UPDATE_REQUEST = 'BEAT_UPDATE_REQUEST'
export const BEAT_UPDATE_SUCCESS = 'BEAT_UPDATE_SUCCESS'
export const BEAT_UPDATE_FAIL = 'BEAT_UPDATE_FAIL'
export const BEAT_UPDATE_RESET = 'BEAT_UPDATE_RESET'

export const BEAT_CREATE_REVIEW_REQUEST = 'BEAT_CREATE_REVIEW_REQUEST'
export const BEAT_CREATE_REVIEW_SUCCESS = 'BEAT_CREATE_REVIEW_SUCCESS'
export const BEAT_CREATE_REVIEW_FAIL = 'BEAT_CREATE_REVIEW_FAIL'
export const BEAT_CREATE_REVIEW_RESET = 'BEAT_CREATE_REVIEW_RESET'
