export const BEAT_LIST_REQUEST = 'BEAT_LIST_REQUEST'
export const BEAT_LIST_SUCCESS = 'BEAT_LIST_SUCCESS'
export const BEAT_LIST_FAIL = 'BEAT_LIST_FAIL'

export const BEAT_DETAILS_REQUEST = 'BEAT_DETAILS_REQUEST'
export const BEAT_DETAILS_SUCCESS = 'BEAT_DETAILS_SUCCESS'
export const BEAT_DETAILS_FAIL = 'BEAT_DETAILS_FAIL'
