const beats = [
  {
    _id: '1',
    name: 'Apple',
    image: '/assets/covers/apple.jpg',
    BPM: 100,
    Key: 'A Minor',
    Description: '',
    Tags: ['Hip-Hop', 'Soul', 'Lo-fi'],
    TypeBeat: ['J Dilla', 'Flying Lotus', 'Kendrick Lamar'],
    price: 499.99,
    countInStock: 1,
    rating: 5.0,
    numReviews: 2,
  },
  {
    _id: '2',
    name: 'Blur',
    image: '/assets/covers/blur.png',
    BPM: 70,
    Key: 'D Minor',
    Description: '',
    Tags: ['Trap', 'Guitar', 'Banger'],
    TypeBeat: ['JuiceWRLD', 'Lil Uzi Vert', 'Money Man'],
    price: 499.99,
    countInStock: 1,
    rating: 5.0,
    numReviews: 10,
  },
  {
    _id: '3',
    name: 'DAWG',
    image: '/assets/covers/dawg.jpg',
    BPM: 50,
    Key: 'F Minor',
    Description: '',
    Tags: ['Trap', 'Banger', 'Aggressive'],
    TypeBeat: ['Future', 'Kendrick Lamar', 'Doe Boy'],
    price: 499.99,
    countInStock: 1,
    rating: 4.9,
    numReviews: 10,
  },
  {
    _id: '4',
    name: 'Ferocious',
    image: '/assets/covers/ferocious.jpg',
    Key: 'Ab Minor',
    Description: '',
    Tags: ['Trap', 'Sad', 'Banger'],
    TypeBeat: ['Lil Yachty', 'Money Man', 'Young Jeezy'],
    price: 499.99,
    countInStock: 1,
    rating: 4.8,
    numReviews: 3,
  },
  {
    _id: '5',
    name: 'Love',
    image: '/assets/covers/love.jpg',
    BPM: 84,
    Key: 'Bb Minor',
    Description: '',
    Tags: ['Hip-Hop', 'R&B', 'Hit'],
    TypeBeat: ['Hitmaka', 'bl#ck', 'Fashawn'],
    price: 499.99,
    countInStock: 1,
    rating: 4.9,
    numReviews: 6,
  },
  {
    _id: '6',
    name: 'Rome',
    image: '/assets/covers/rome.jpg',
    BPM: 60,
    Key: 'C Minor',
    Description: '',
    Tags: ['Trap', 'Banger', 'Dark'],
    TypeBeat: ['Future', 'Drake', 'Geto Boys'],
    price: 499.99,
    countInStock: 1,
    rating: 4.5,
    numReviews: 5,
  },
]

export default beats
